In [65]:
import pandas as pd

stats = pd.read_csv('playerMvpStats.csv')

#highest_scoring = stats[stats['G'] > 70].sort_values('PTS', ascending=False).head(10)
#highest_scoring

stats

,Unnamed: 0,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,0,Alan Henderson,SF,26,ATL,38,37,30.1,4.9,11.1,...,0.0,0.0,Atlanta Hawks,31,19,0.620,2.0,86.3,83.4,2.82
1,1,Anthony Johnson,PG,24,ATL,49,2,18.1,1.9,4.6,...,0.0,0.0,Atlanta Hawks,31,19,0.620,2.0,86.3,83.4,2.82
2,2,Chris Crawford,PF,23,ATL,42,30,18.7,2.6,6.1,...,0.0,0.0,Atlanta Hawks,31,19,0.620,2.0,86.3,83.4,2.82
3,3,Dikembe Mutombo,C,32,ATL,50,50,36.6,3.5,6.8,...,0.0,0.0,Atlanta Hawks,31,19,0.620,2.0,86.3,83.4,2.82
4,4,Ed Gray,SG,23,ATL,30,3,11.2,1.8,6.1,...,0.0,0.0,Atlanta Hawks,31,19,0.620,2.0,86.3,83.4,2.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11954,11954,Monte Morris,PG,27,WAS,62,61,27.3,4.0,8.3,...,0.0,0.0,Washington Wizards,35,47,0.427,9.0,113.2,114.4,-1.06
11955,11955,Quenton Jackson,PG,24,WAS,9,0,15.0,2.1,4.7,...,0.0,0.0,Washington Wizards,35,47,0.427,9.0,113.2,114.4,-1.06
11956,11956,Taj Gibson,C,37,WAS,49,2,9.8,1.3,2.6,...,0.0,0.0,Washington Wizards,35,47,0.427,9.0,113.2,114.4,-1.06
11957,11957,Vernon Carey Jr.,C,21,WAS,11,0,2.5,0.2,0.7,...,0.0,0.0,Washington Wizards,35,47,0.427,9.0,113.2,114.4,-1.06
11958,11958,Xavier Cooks,PF,27,WAS,10,1,12.6,1.7,2.8,...,0.0,0.0,Washington Wizards,35,47,0.427,9.0,113.2,114.4,-1.06

In [66]:
del stats["Unnamed: 0"]

In [67]:
pd.isnull(stats).sum() #AI Algo doesn't like null values. Find sum of null values fo each coloumn

Player        0
Pos           0
Age           0
Tm            0
G             0
GS            0
MP            0
FG            0
FGA           0
FG%          48
3P            0
3PA           0
3P%        1586
2P            0
2PA           0
2P%          91
eFG%         48
FT            0
FTA           0
FT%         472
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Year          0
Pts Won       0
Pts Max       0
Share         0
Team          0
W             0
L             0
W/L%          0
GB            0
PS/G          0
PA/G          0
SRS           0
dtype: int64

In [68]:
stats[pd.isnull(stats['FT%'])][['Player','FTA']]

                 Player  FTA
28           Andy Panko  0.0
35           Ira Bowman  0.0
47      Dickey Simpkins  0.0
63       Antonio Harvey  0.0
64     Brandon Williams  0.0
...                 ...  ...
11926        Joel Ayayi  0.0
11927    Jordan Goodwin  0.0
11936    Tremont Waters  0.0
11944      Devon Dotson  0.0
11950    Jordan Schakel  0.0

[472 rows x 2 columns]

In [69]:
stats = stats.fillna(0)

In [70]:
stats.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Pts Won', 'Pts Max', 'Share', 'Team', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS'],
      dtype='object')

In [71]:
predictors = ['Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
        'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS'] #only retain numeric values that do notdirectly correlate with outcome (aka MVP pts)

In [72]:
train = stats[stats['Year'] < 2023]

In [73]:
test = stats[stats['Year'] == 2023]

In [74]:
from sklearn.linear_model import Ridge

reg = Ridge(alpha=.1)

In [75]:
reg.fit(train[predictors], train['Share'])

Ridge(alpha=0.1)

In [76]:
predictions = reg.predict(test[predictors])

In [77]:
predictions = pd.DataFrame(predictions, columns=['Predictions'],index = test.index)

In [78]:
predictions

       Predictions
386      -0.017544
387      -0.024488
388      -0.004528
389      -0.011246
390       0.021988
...            ...
11954     0.003629
11955    -0.004608
11956    -0.020476
11957    -0.006636
11958    -0.020535

[539 rows x 1 columns]

In [79]:
combination = pd.concat([test[['Player', 'Share']], predictions], axis =1)

In [80]:
combination

                  Player  Share  Predictions
386           AJ Griffin    0.0    -0.017544
387        Aaron Holiday    0.0    -0.024488
388    Bogdan Bogdanović    0.0    -0.004528
389       Bruno Fernando    0.0    -0.011246
390         Clint Capela    0.0     0.021988
...                  ...    ...          ...
11954       Monte Morris    0.0     0.003629
11955    Quenton Jackson    0.0    -0.004608
11956         Taj Gibson    0.0    -0.020476
11957   Vernon Carey Jr.    0.0    -0.006636
11958       Xavier Cooks    0.0    -0.020535

[539 rows x 3 columns]

In [81]:
combination.sort_values('Share', ascending=False).head(10)

                        Player  Share  Predictions
8968               Joel Embiid  0.915     0.189213
2977              Nikola Jokić  0.674     0.173890
6549     Giannis Antetokounmpo  0.606     0.220140
787               Jayson Tatum  0.280     0.135139
8172   Shai Gilgeous-Alexander  0.046     0.135730
2169          Donovan Mitchell  0.030     0.082146
10134         Domantas Sabonis  0.027     0.095524
2583               Luka Dončić  0.010     0.193129
3767             Stephen Curry  0.005     0.111332
6156              Jimmy Butler  0.003     0.100272

In [82]:
from sklearn.metrics import mean_squared_error

mean_squared_error(combination['Share'], combination['Predictions'])

0.0026485958117314374

In [83]:
combination['Share'].value_counts()

Share
0.000    526
0.001      2
0.280      1
0.030      1
0.010      1
0.674      1
0.005      1
0.003      1
0.606      1
0.046      1
0.915      1
0.002      1
0.027      1
Name: count, dtype: int64

In [84]:
combination = combination.sort_values('Share', ascending=False)
combination['Rank'] = list(range(1,combination.shape[0]+1))

In [85]:
combination.head(10)

                        Player  Share  Predictions  Rank
8968               Joel Embiid  0.915     0.189213     1
2977              Nikola Jokić  0.674     0.173890     2
6549     Giannis Antetokounmpo  0.606     0.220140     3
787               Jayson Tatum  0.280     0.135139     4
8172   Shai Gilgeous-Alexander  0.046     0.135730     5
2169          Donovan Mitchell  0.030     0.082146     6
10134         Domantas Sabonis  0.027     0.095524     7
2583               Luka Dončić  0.010     0.193129     8
3767             Stephen Curry  0.005     0.111332     9
6156              Jimmy Butler  0.003     0.100272    10

In [86]:
combination = combination.sort_values('Predictions', ascending=False)
combination['Predicted Rank'] = list(range(1,combination.shape[0]+1))

In [87]:
combination.head(10)

                       Player  Share  Predictions  Rank  Predicted Rank
6549    Giannis Antetokounmpo  0.606     0.220140     3               1
2583              Luka Dončić  0.010     0.193129     8               2
8968              Joel Embiid  0.915     0.189213     1               3
2977             Nikola Jokić  0.674     0.173890     2               4
9740           Damian Lillard  0.000     0.142901   225               5
8172  Shai Gilgeous-Alexander  0.046     0.135730     5               6
9360             Kevin Durant  0.000     0.135330   234               7
787              Jayson Tatum  0.280     0.135139     4               8
5364            Anthony Davis  0.000     0.127517   415               9
5371             LeBron James  0.000     0.125801   441              10

In [88]:
combination.sort_values('Share', ascending=False).head(10)

                        Player  Share  Predictions  Rank  Predicted Rank
8968               Joel Embiid  0.915     0.189213     1               3
2977              Nikola Jokić  0.674     0.173890     2               4
6549     Giannis Antetokounmpo  0.606     0.220140     3               1
787               Jayson Tatum  0.280     0.135139     4               8
8172   Shai Gilgeous-Alexander  0.046     0.135730     5               6
2169          Donovan Mitchell  0.030     0.082146     6              22
10134         Domantas Sabonis  0.027     0.095524     7              16
2583               Luka Dončić  0.010     0.193129     8               2
3767             Stephen Curry  0.005     0.111332     9              13
6156              Jimmy Butler  0.003     0.100272    10              15

In [89]:
def find_ap(combination):
    actual = combination.sort_values('Share', ascending=False).head(5)
    predicted = combination.sort_values('Predictions', ascending=False)
    ps = []
    found = 0
    seen = 1
    for index, row in predicted.iterrows():
        if row['Player'] in actual['Player'].values:
            found += 1
            ps.append(found/seen)
        seen += 1
    return sum(ps) / len(ps)

In [90]:
find_ap(combination)

0.7416666666666666

In [91]:
years = list(range(1999, 2024))

In [113]:
aps = []
all_predictions = []
for year in years[5:]:
    train = stats[stats['Year'] < year]
    test = stats[stats['Year'] == year]
    reg.fit(train[predictors], train['Share'])
    predictions = reg.predict(test[predictors])
    predictions = pd.DataFrame(predictions, columns=['Predictions'], index = test.index)
    combination = pd.concat([test[['Player', 'Share']], predictions], axis=1)
    all_predictions.append(combination)
    aps.append(find_ap(combination))

In [114]:
sum(aps) / len(aps)

0.6765025563129143

In [115]:
def add_ranks(combination):
    combination = combination.sort_values('Share', ascending=False)
    combination['Rank'] = list(range(1,combination.shape[0]+1))
    combination = combination.sort_values('Predictions', ascending=False)
    combination['Predicted Rank'] = list(range(1,combination.shape[0]+1))
    combination['Diff'] = combination['Rank'] - combination['Predicted Rank']
    return combination

In [117]:
rankings = add_ranks(all_predictions[1])
rankings[rankings['Rank'] < 6].sort_values('Diff', ascending=False)

                 Player  Share  Predictions  Rank  Predicted Rank  Diff
10249        Tim Duncan  0.258     0.170040     4               2     2
5860   Shaquille O'Neal  0.813     0.268265     2               1     1
2277      Dirk Nowitzki  0.275     0.119747     3               7    -4
8665      Allen Iverson  0.189     0.079852     5              13    -8
9076         Steve Nash  0.839     0.048842     1              34   -33

In [142]:
def backtest(stats, model, year, predictors):
    aps = []
    all_predictions = []
    for year in years[5:]:
        train = stats[stats['Year'] < year]
        test = stats[stats['Year'] == year]
        model.fit(train[predictors], train['Share'])
        predictions = reg.predict(test[predictors])
        predictions = pd.DataFrame(predictions, columns=['Predictions'], index = test.index)
        combination = pd.concat([test[['Player', 'Share']], predictions], axis=1)
        combination = add_ranks(combination)
        all_predictions.append(combination)
        aps.append(find_ap(combination))
    return sum(aps)/len(aps), aps, pd.concat(all_predictions)

In [143]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [144]:
mean_ap

0.6765025563129143

In [145]:
all_predictions[all_predictions['Rank'] <= 5].sort_values('Diff').head(10)

                Player  Share  Predictions  Rank  Predicted Rank  Diff
9837   Peja Stojaković  0.228     0.012352     4             125  -121
1597       Joakim Noah  0.258     0.045565     4              37   -33
9076        Steve Nash  0.839     0.048842     1              34   -33
3091  Chauncey Billups  0.344     0.052871     5              35   -30
9314        Chris Paul  0.138     0.069607     5              33   -28
9094        Steve Nash  0.739     0.076118     1              23   -22
5061       Kobe Bryant  0.172     0.057651     5              21   -16
5148       Kobe Bryant  0.487     0.077979     3              14   -11
9335      Devin Booker  0.216     0.085887     4              15   -11
5178       Kobe Bryant  0.291     0.066896     4              15   -11

In [148]:
pd.concat([pd.Series(reg.coef_), pd.Series(predictors)], axis=1).sort_values(0, ascending=False)

           0     1
13  0.094088  eFG%
18  0.037174   DRB
29  0.029199  W/L%
17  0.026360   ORB
15  0.011803   FTA
25  0.011264   PTS
12  0.011070   2P%
22  0.008833   BLK
21  0.007785   STL
20  0.007322   AST
4   0.005351    FG
10  0.003750    2P
30  0.000298    GB
27  0.000194     W
1   0.000069     G
0   0.000053   Age
2  -0.000006    GS
28 -0.000264     L
31 -0.000268  PS/G
32 -0.000279  PA/G
26 -0.000482  Year
33 -0.000792   SRS
5  -0.001152   FGA
3  -0.003473    MP
16 -0.003682   FT%
24 -0.004013    PF
23 -0.004282   TOV
8  -0.004344   3PA
9  -0.011385   3P%
11 -0.011422   2PA
14 -0.011855    FT
7  -0.013681    3P
19 -0.030614   TRB
6  -0.159322   FG%

In [149]:
stat_ratios = stats[['PTS', 'AST', 'STL', 'BLK', '3P', 'Year']].groupby('Year').apply(lambda x: x/x.mean())

C:\Users\abous\AppData\Local\Temp\ipykernel_3332\611064546.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stat_ratios = stats[['PTS', 'AST', 'STL', 'BLK', '3P', 'Year']].groupby('Year').apply(lambda x: x/x.mean())

In [155]:
stat_ratios.index = stat_ratios.index.droplevel()
stat_ratios

            PTS       AST       STL       BLK        3P  Year
0      1.702049  0.424009  1.333333  1.246459  0.000000   1.0
1      0.680819  1.332599  1.037037  0.249292  0.283140   1.0
2      0.939531  0.363436  0.296296  0.747875  0.849421   1.0
3      1.470570  0.666300  0.444444  7.229462  0.000000   1.0
4      0.667203  0.242291  0.592593  0.000000  1.132561   1.0
...         ...       ...       ...       ...       ...   ...
11954  1.129221  2.561833  1.148205  0.523047  1.312418   1.0
11955  0.679725  0.821720  0.656117  0.261524  0.100955   1.0
11956  0.372752  0.338355  0.492088  0.523047  0.201910   1.0
11957  0.054817  0.145009  0.328058  0.523047  0.000000   1.0
11958  0.416606  0.290019  0.984175  1.046094  0.000000   1.0

[11959 rows x 6 columns]

In [156]:
stats[['PTS_T', 'AST_R', 'STL_R', 'BLK_R', '3P_R']] = stat_ratios[['PTS', 'AST', 'STL', 'BLK', '3P']]

In [159]:
stats.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,W/L%,GB,PS/G,PA/G,SRS,PTS_T,AST_R,STL_R,BLK_R,3P_R
0,Alan Henderson,SF,26,ATL,38,37,30.1,4.9,11.1,0.442,...,0.62,2.0,86.3,83.4,2.82,1.702049,0.424009,1.333333,1.246459,0.000000
1,Anthony Johnson,PG,24,ATL,49,2,18.1,1.9,4.6,0.404,...,0.62,2.0,86.3,83.4,2.82,0.680819,1.332599,1.037037,0.249292,0.283140
2,Chris Crawford,PF,23,ATL,42,30,18.7,2.6,6.1,0.431,...,0.62,2.0,86.3,83.4,2.82,0.939531,0.363436,0.296296,0.747875,0.849421
3,Dikembe Mutombo,C,32,ATL,50,50,36.6,3.5,6.8,0.512,...,0.62,2.0,86.3,83.4,2.82,1.470570,0.666300,0.444444,7.229462,0.000000
4,Ed Gray,SG,23,ATL,30,3,11.2,1.8,6.1,0.291,...,0.62,2.0,86.3,83.4,2.82,0.667203,0.242291,0.592593,0.000000,1.132561

In [160]:
predictors += ['PTS_T', 'AST_R', 'STL_R', 'BLK_R', '3P_R']

In [161]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [162]:
mean_ap

0.6898667240663269

In [164]:
stats['NPos'] = stats['Pos'].astype('category').cat.codes

In [167]:
stats['NTm'] = stats['Tm'].astype('category').cat.codes

In [169]:
stats.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,PS/G,PA/G,SRS,PTS_T,AST_R,STL_R,BLK_R,3P_R,NPos,NTm
0,Alan Henderson,SF,26,ATL,38,37,30.1,4.9,11.1,0.442,...,86.3,83.4,2.82,1.702049,0.424009,1.333333,1.246459,0.000000,8,0
1,Anthony Johnson,PG,24,ATL,49,2,18.1,1.9,4.6,0.404,...,86.3,83.4,2.82,0.680819,1.332599,1.037037,0.249292,0.283140,5,0
2,Chris Crawford,PF,23,ATL,42,30,18.7,2.6,6.1,0.431,...,86.3,83.4,2.82,0.939531,0.363436,0.296296,0.747875,0.849421,2,0
3,Dikembe Mutombo,C,32,ATL,50,50,36.6,3.5,6.8,0.512,...,86.3,83.4,2.82,1.470570,0.666300,0.444444,7.229462,0.000000,0,0
4,Ed Gray,SG,23,ATL,30,3,11.2,1.8,6.1,0.291,...,86.3,83.4,2.82,0.667203,0.242291,0.592593,0.000000,1.132561,12,0

In [170]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=50, random_state=1, min_samples_split=5)

mean_ap, aps, all_predictions = backtest(stats, rf, years[5:], predictors)

mean_ap

0.7459990567077033